# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator.xci
# IP: The module: 'Clock_Generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_Generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_Generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_Generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator.xci
# IP: The module: 'Clock_Generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_Generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_Generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/VGA_Display/VGA_Display.srcs/sources_1/ip/Clock_Generator/Clock_Generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_Generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
