webtalk_init -webtalk_dir C:/git/VHDL/Camera_Display/Camera_Display.sim/sim_1/behav/xsim/xsim.dir/TB_I2C_Controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 27 17:58:47 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "274c043d-86bb-49c4-9ce0-5172d3e7a536" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3b85e67a665340bdb6fbfb6364d9dadb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "50" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14844_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1843286080 -regid "" -xml C:/git/VHDL/Camera_Display/Camera_Display.sim/sim_1/behav/xsim/xsim.dir/TB_I2C_Controller_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/git/VHDL/Camera_Display/Camera_Display.sim/sim_1/behav/xsim/xsim.dir/TB_I2C_Controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/git/VHDL/Camera_Display/Camera_Display.sim/sim_1/behav/xsim/xsim.dir/TB_I2C_Controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
