@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Nov 02 18:30:31 +0000 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 3b85e67a665340bdb6fbfb6364d9dadb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_I2C_Controller_behav xil_defaultlib.TB_I2C_Controller -log elaborate.log"
call xelab  -wto 3b85e67a665340bdb6fbfb6364d9dadb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_I2C_Controller_behav xil_defaultlib.TB_I2C_Controller -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
