@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun May 23 17:28:02 +0100 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto c0d69525b5a8464d99af9c562799a450 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_Logical_Unit_behav xil_defaultlib.TB_Logical_Unit -log elaborate.log"
call xelab  -wto c0d69525b5a8464d99af9c562799a450 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_Logical_Unit_behav xil_defaultlib.TB_Logical_Unit -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
